//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public short incident_number { get; set; }
        public string incident_action_taken { get; set; }
        public string incident_diagnosis { get; set; }
        public string incident_callout_time { get; set; }
        public string patient_nhs_registration { get; set; }
        public Nullable<short> assigned_hospital { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
